### ISSUE TITLE
Doesn't build with iOS 13.1 SDK

### ISSUE THREAD

**Issue by woolie** [mattgallagher/CwlPreconditionTesting#19]
Seems to have a problem compiling with the iOS 13.1 SDK in place.

```
public let x86_THREAD_STATE64_COUNT = UInt32(MemoryLayout<x86_thread_state64_t>.size / MemoryLayout<Int32>.size)
                                                          ^~~~~~~~~~~~~~~~~~~~
/Users/woolie/Library/Developer/Xcode/DerivedData/Crushroom-gcriwdpohkxdulcyaqptkqvtrnch/SourcePackages/checkouts/CwlPreconditionTesting/Sources/CwlPreconditionTesting/CwlBadInstructionException.swift:63:47: error: use of unresolved identifier 'x86_thread_state64_t'
                var state = old_state.withMemoryRebound(to: x86_thread_state64_t.self, capacity: 1) { return $0.pointee }
                                                            ^~~~~~~~~~~~~~~~~~~~
/Users/woolie/Library/Developer/Xcode/DerivedData/Crushroom-gcriwdpohkxdulcyaqptkqvtrnch/SourcePackages/checkouts/CwlPreconditionTesting/Sources/CwlPreconditionTesting/CwlBadInstructionException.swift:82:35: error: use of unresolved identifier 'x86_thread_state64_t'
                new_state.withMemoryRebound(to: x86_thread_state64_t.self, capacity: 1) { $0.pointee = state }
```

**Comment by woolie** [comment]
Don't know what I was smoking?
